Itanio.Leads.WebUI/Models/ArquivoViewModel.cs
using System;
using System.Collections.Generic;
using Carubbi.Datatables;
using Itanio.Leads.Domain.Entidades;

namespace Itanio.Leads.WebUI.Models
{
    public class ArquivoViewModel
    {
        [DataTablesColumn(Hidden = true, PrimaryKey = true)]
        public string Id { get; set; }

        [DataTablesColumn(Order = 1, Header = "Nome")]
        public string NomeArquivo { get; set; }

        public bool Ativo { get; set; }

        [DataTablesColumn(Order = 2, SortMap = "Ativo", Header = "Ativo")]
        public string AtivoDescr => Ativo
            ? "Sim"
            : "Não";

        [DataTablesColumn(Order = 3, Header = "URL")]
        public string Url { get; set; }

        internal static ArquivoViewModel FromEntity(Arquivo arquivo)
        {
            return new ArquivoViewModel
            {
                Id = arquivo.Id.ToString(),
                NomeArquivo = arquivo.NomeArquivo,
                Ativo = arquivo.Ativo,
                Url = arquivo.Url
            };
        }

        internal static Arquivo ToEntity(ArquivoViewModel viewModel, Projeto projeto)
        {
            return new Arquivo
            {
                Ativo = viewModel.Ativo,
                Id = !string.IsNullOrWhiteSpace(viewModel.Id) ? new Guid(viewModel.Id) : Guid.Empty,
                NomeArquivo = viewModel.NomeArquivo,
                Projeto = projeto,
                Url = viewModel.Url
            };
        }

        internal static IEnumerable<ArquivoViewModel> FromEntityCollection(IEnumerable<Arquivo> entities)
        {
            foreach (var item in entities) yield return FromEntity(item);
        }
    }
}

Itanio.Leads.WebUI/Controllers/ArquivoController.cs
using System;
using System.Web.Mvc;
using Itanio.Leads.Domain;
using Itanio.Leads.Domain.Entidades;
using Itanio.Leads.Domain.Repositorios;
using Itanio.Leads.WebUI.ActionResults;

namespace Itanio.Leads.WebUI.Controllers
{
    [AllowAnonymous]
    public class ArquivoController : BaseController
    {
        public ArquivoController(IContexto contexto)
            : base(contexto)
        {
        }

        // GET: Arquivo
        public ActionResult Index(string id, string guid)
        {
            var arquivoRepo = new RepositorioArquivo(_contexto);
            var arquivo = arquivoRepo.ObterPorId(new Guid(id));
            var visitanteRepo = new RepositorioVisitante(_contexto);
            var visitante = visitanteRepo.ObterPorIdentificador(guid);
            ViewBag.Url = arquivo.Projeto.UrlBase + "/" + arquivo.Projeto.LandPage + $"?IdArquivo={arquivo.Id}";

            var acesso = new Acesso();
            acesso.IP = HttpContext.Request.ServerVariables["REMOTE_ADDR"];
            var projeto = arquivo.Projeto;
            var acessoRepo = new RepositorioAcesso(_contexto);

            acesso.Visitante = visitante;
            acesso.Projeto = projeto;
            acesso.Arquivo = arquivo;
            acesso.DataHoraAcesso = DateTime.Now;
            acesso.Ativo = true;
            acesso.Guid = guid;
            acesso.UserAgent = HttpContext.Request.UserAgent;

            if (visitante == null)
            {
                acesso.Url = "ArquivoNaoDisponivel";
                acessoRepo.Gravar(acesso);
                return View("ArquivoNaoDisponivel");
            }

            acesso.Url = $"{arquivo.Url}/{arquivo.NomeArquivo}";
            acessoRepo.Gravar(acesso);

            return new ExternalFileResult(acesso.Url);
        }
    }
}

Itanio.Leads.WebUI/Views/Arquivo/ArquivoNaoDisponivel.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Leads - Login</title>
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/css")
</head>
<body class="top-navigation">
<div id="wrapper">
    <div id="page-wrapper" class="gray-bg">
        <div class="wrapper wrapper-content">
            <div class="container">
                <div class="row">
                    <div class="jumbotron text-center">
                        <h1>Você não possui acesso a este conteúdo, para baixar acesse <a href="@ViewBag.Url">aqui</a> e preencha seu nome e e-mail.</h1>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="footer">
    <div>
        <strong>Copyright</strong> Itanio © 2016-2016
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Itanio.Leads.WebUI/Views/Arquivo/_ArquivosGrid.cshtml
@using Itanio.Leads.WebUI.Models
<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>@Html.Label("Arquivos", new { @class = "control-label" })</h5>
    </div>
    <div class="ibox-content">
        <div class="form-group">
            @Html.Table("Arquivos", new List<ArquivoViewModel>(),
                        new
                        {
                            @class = "table table-striped table-bordered table-hover datatables",
                            data_action = Url.Action("Arquivos", "Arquivo"),
                            data_allow_edit = true,
                            data_allow_delete = true,
                            data_edit_mode = EditMode.Modal,
                            data_edit_action = Url.Action("Editar", "Arquivo"),
                            data_allow_new = true,
                            data_delete_action = Url.Action("Excluir", "Arquivo"),
                        })
        </div>
    </div>
</div>